_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_3x.yml',
  '_base_/dino_r50vd_pan.yml',
  '_base_/yoloe_reader.yml',
]

weights: output/dino_r50vd_pan_4_0_6_3x_coco/model_final
find_unused_parameters: True
log_iter: 100
snapshot_epoch: 2
